---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "40"
year: "2021"
contributor: 
- "Redaktion LIBREAS"
title: "Editorial #40: Dekolonisierung"
pdf: "https://doi.org/10.18452/23802"
doi: "10.18452/23802"
date: 2021-12-19
comments: false
sharing: true
footer: true

---