---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "40"
year: "2021"
contributor: 
- Sandra Sparber
title: "kolonial geordnet: die historische Bestandsanalyse als Methode zum Aufspüren von Othering in Bibliotheksbeständen
"
pdf: "https://doi.org/10.18452/23803"
doi: "10.18452/23803"
date: 2021-12-22
comments: false
sharing: true
footer: true

---