---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "40"
year: "2021"
contributor: 
- "Yvonne Schürer"
title: "Warum beschäftige ich mich mit dem Dekolonialisieren von Bibliotheken?"
pdf: "main.pdf"
doi: "10.18452/23809"
date: 2021-12-19
comments: false
sharing: true
footer: true

---