---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "40"
year: "2021"
contributor: 
- Nora Schmidt
title: "Überlegungen für die Dekolonialisierung wissenschaftlicher Bibliotheken in Europa
"
pdf: "https://doi.org/10.18452/23808"
doi: "10.18452/23808"
date: 2021-12-22
comments: false
sharing: true
footer: true

---