---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "40"
year: "2021"
contributor: 
- "Matthias Harbeck"
title: "Die Ethik des Digitalisierens: Fragen zum Umgang mit Materialien aus kolonialen Kontexten in der Massendigitalisierung"
pdf: "https://doi.org/10.18452/23806"
doi: "10.18452/23806"
date: 2021-12-19
comments: false
sharing: true
footer: true

---