---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "40"
year: "2021"
contributor: 
- "Gabriele Slezak"
- "Sarah Schmelzer"
- "Andrea Ruscher"
- "Jonas Paintner"
- "Erem Celebi"
- "Dani Baumgartner"
title: "Rassismen im Bücherregal? Ein Praxisbericht von der kolonialen Spurensuche in der Bibliothek bis hin zu einer rassismuskritischen Bildung"
abstract: "Bibliotheken verwalten Wissen. Bibliotheken sind Räume für Menschen. Was passiert, wenn all das auf kolonialer Vergangenheit aufbaut? Die C3-Bibliothek für Entwicklungspolitik in Wien hat 2018 begonnen, sich aktiv mit der eigenen Geschichte rassistischer Praktiken auseinanderzusetzen. Wir verstehen Dekolonialisierung von Bibliotheken als Prozess, der aktiv gestaltet werden muss. Dieser braucht einen Kompetenzaufbau für die inhaltliche Auseinandersetzung mit Rassismen in überwiegend weißen Institutionen durch Erwerben von theoretischem Wissen und kritische, selbstreflexive Auseinandersetzung mit rassistischen Denkweisen wie auch eine diskursive und partizipative Ausgestaltung mit breiter Einbindung der Akteur*innen. Damit Letzteres gelingen kann gilt es auf der Ebene der Nutzer*innen und Bürger*innen eine direkte und offene Thematisierung zu initiieren, die aktive Teilhabe und Engagement aller an der Debatte fördert. Für die C3-Bibiothek ist dafür die Vermittlung von Informationskompetenz als transformatorisches Werkzeug zentral. Sie ermöglicht ein Engagement, das sich manipulativen, entmenschlichenden und kolonisierenden Prinzipien widersetzen kann. Der Beitrag stellt erste Erfahrungen aus der Praxis und Reflexionsergebnisse dem Austausch mit gleichgesinnten Bibliotheken im deutschsprachigen Raum zur Verfügung."
pdf: "https://doi.org/10.18452/23805"
doi: "10.18452/23805"
date: 2021-12-19
comments: false
sharing: true
footer: true

---