---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "40"
year: "2021"
contributor: 
- "Gabriele Slezak"
- "Sarah Schmelzer"
- "Andrea Ruscher"
- "Jonas Paintner"
- "Erem Celebi"
- "Dani Baumgartner"
title: "Rassismen im Bücherregal? Ein Praxisbericht von der kolonialen Spurensuche in der Bibliothek bis hin zu einer rassismuskritischen Bildung"
abstract: "Der Rückgriff auf kontrollierte Vokabulare und Normdaten ist im Zuge der Zugänglichmachung von analogen und digitalen Ressourcen zentral. Der vorliegende Text diskutiert (ethisch-theoretische) Fragestellungen im Umgang mit kontrollierten Vokabularen als spezifisch eurozentrische Wissensordnungen."
pdf: "https://doi.org/10.18452/23805"
doi: "10.18452/23805"
date: 2021-12-19
comments: false
sharing: true
footer: true

---