---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "40"
year: "2021"
contributor: 
- "Moritz Strickert"
title: "Zwischen Normierung und Offenheit – Potenziale und offene Fragen bezüglich kontrollierter Vokabulare und Normdateien"
abstract: "Der Rückgriff auf kontrollierte Vokabulare und Normdaten ist im Zuge der Zugänglichmachung von analogen und digitalen Ressourcen zentral. Der vorliegende Text diskutiert (ethisch-theoretische) Fragestellungen im Umgang mit kontrollierten Vokabularen als spezifisch eurozentrische Wissensordnungen."
pdf: "https://doi.org/10.18452/23807"
doi: "10.18452/23807"
date: 2021-12-19
comments: false
sharing: true
footer: true

---