---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "40"
year: "2021"
contributor: 
- "Redaktion LIBREAS"
title: "Das liest die LIBREAS, Nummer #9 (Herbst / Winter 2021)"
pdf: "https://doi.org/10.18452/..."
doi: "10.18452/..."
date: 2021-12-19
comments: false
sharing: true
footer: true

---