---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "40"
year: "2021"
contributor: 
- "Birgit Kramreither"
title: "Ethnographische Forschungsdaten – eine Verantwortung!"
abstract: "Die Geschichte des Fachs Kultur- und Sozialanthropologie in Wien spiegelt sich im Literaturbestand der Fachbereichsbibliothek Kultur- und Sozialanthropologie wider. Aus heutiger Sicht muss mit ethnographischem Datenmaterial zum Schutz der Beforschten sehr sorgsam umgegangen werden. Die Verantwortung darüber liegt nicht zuletzt bei Repositorien, Archiven und Bibliotheken."
pdf: "https://doi.org/10.18452/23810.2"
doi: "10.18452/23810.2"
date: 2021-12-19
comments: false
sharing: true
footer: true

---