---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "40"
year: "2021"
contributor: 
- "Elisa Frei"
title: "Wenn aus <q>Menschenfressern</q> Affen werden"
subtitle: "Rassismen in Bibliotheken am Beispiel von <q>Hatschi Bratschis Luftballon</q>"
abstract: "Dieser Artikel thematisiert den Umgang von Bibliotheken mit Medien, deren Inhalte Rassismen enthalten, exemplarisch anhand des rassistischen Kinderbuches <q>Hatschi Bratschis Luftballon</q> von Franz Karl Ginzkey in den Büchereien Wien und der Fachbereichsbibliothek für Germanistik, Nederlandistik und Skandinavistik. Die Grundlage der Untersuchung bilden zwei Expert:inneninterviews, die mit Vertreter:innen der beiden Institutionen geführt wurden. Ziel des Artikels ist es, die unterschiedlichen Argumentationen der beiden Bibliotheken für die Aufnahme des Kinderbuchs in den jeweiligen Bestand darzustellen. Die Gegenüberstellung der Argumentationen beider Bibliotheksarten – bei den Büchereien Wien handelt es sich um eine öffentliche und bei der Fachbereichsbibliothek um eine wissenschaftliche Bibliothek – zeigen, dass diese aufgrund von Bestandspolitik und Zielpublikum divergieren, zum Teil aber mit ähnlichen Fragen und Herausforderungen konfrontiert sind."
abstractalt: "In this article the handling of libraries with information sources that contain racism is examined by the racist children’s book <q>Hatschi Bratschis Luftballon</q> by Franz Karl Ginzkey in the Büchereien Wien and the Fachbereichsbibliothek für Germanistik, Nederlandistik und Skandinavistik. Two expert interviews which were conducted with representatives of both institutions provide the basis for this analysis. The purpose of this article is to describe the different argumentations of the libraries to include the children’s book into their library collections. The comparison of the arguments of both types of libraries – the Büchereien Wien are public and the Fachbereichsbibliothek is a scientific library – show that they diverge due to inventory policy and their target audience, however, they are confronted with similar questions and challenges."
pdf: "main.pdf"
doi: "10.18452/23804"
date: 2021-12-19
comments: false
sharing: true
footer: true

---