---

layout: page
lang: "de,en,pt"
journal: "LIBREAS. Library Ideas"
issue: "40"
year: "2021"
contributor: 
- Valentina de Toledo
- Franciéle Garcês
title: "<Rassismus ist ein weißes Thema, warum sollten sich nur Schwarze in ihrer Lehre und Berufspraxis damit befassen?>
Die Bibliothekarin Franciéle Garcês berichtet über den Einfluss des Weißseins im Feld der Bibliotheks- und Informationswissenschaft und die Fortdauer des Rassismus im Bibliothekswesen und in der Informationswissenschaft."
pdf: "main.pdf"
date: 2021-12-23
comments: false
sharing: true
footer: true

---