---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "40"
year: "2021"
contributor: 
- Valentina de Toledo
- Franciéle Garcês
title: "<q>Rassismus ist ein weißes Thema, warum sollten sich nur Schwarze in ihrer Lehre und Berufspraxis damit befassen?</q>"
abstract: "Die Bibliothekarin Franciéle Garcês berichtet über den Einfluss des Weißseins im Feld der Bibliotheks- und Informationswissenschaft und die Fortdauer des Rassismus im Bibliothekswesen und in der Informationswissenschaft."
abstractalt: "Librarian Franciéle Garcês tells about the influence of whiteness in the librarianship-information science field and the perpetuation of racism in librarianship and information science."
pdf: "https://doi.org/10.18452/23800"
doi: "10.18452/23800"
date: 2021-12-23
comments: false
sharing: true
footer: true

---